version: '3'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any

volumes:
  caddy_data:

networks:
  caddy:
    driver: overlay
