version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      PAT: ${PAT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
    restart: always
  db:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    image: postgres:latest
    ports:
      - 5432:5432
