version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev

    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      WORKER: 'http://worker:8086/process'
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
    restart: always
  worker:
    build:
      context: ../audioprocessing
    restart: always
    volumes:
      - ../audioprocessing/:/src
      - /src/node_modules
    environment:
      PORT: 8086
